version: '{build}'

branches:
  only:
  - master
clone_folder: c:\projects\cmake-init
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x86
environment:
  matrix:
  - arch: Win32
  my_variable:
    secure: 90KPrB4EWkQ7u+OKQGKmXF/uqC2AI/mnVhYIqg9XqV0tWkTQJ+aKVpg62tWUrXlPjDdG2GuWwZlo6qBp04v8gi6CLEoDPYej6H3B5NJVsgJdGEM+GNvdnuNfIt6W7KBFd7+bz1Za7CfMFTT1H+BBnI+43COA0hbfbzhzndwW82oTcs3HREYfRIplbKBk+pyDtqAtLJpDg1bUiztsvJA/fQB8Hck6w7tTrK/zi73I3CWMA1bzKjAlC5O9ikRW2KYqLaVSLXhGPjwZRmM02el5CqLKZqTGN133IDIdtIxjTag6raOMklErIGdHN+T6Ki99oe4ooq93xn8bxQKMRrfK1k4juot14j7Kc2khNIMNmwbJQGEqLCXnDHtChuT6WxkNvKJ7WgsTtxLqV0r6s9cKJsp3kF4qJjsGGCgomaWbqcQ28tFBkChNl0lkcIeJ9eTX6OoGahgU8Y+T5K6+5dMvQz7dO0aWWVNKQy4/Yarg8LbEFhQea67H2SoGI9aMhcI+B/aQYsYEHH04x9dia/aZV6Ez+2YPNJbe5/q3cuHqi5ZbXdJZcEvuu9hTVlaLm/K/r9XKPfVTIwC8PnbGMATJzCYETXdSujOK/rbP9JSTxA1AxIu6o/suzG6FdmQSHd+2gAmKmafDh5/1n1Ai/0ktwHkyzxN6lFu5ZgEqe3dxk7Obdo8Keky9CekQoRaGG5HhMR0UVqoocge3A3608gbKlJnifn+BjKgNyb68OjFkITKbeTbRA6t7MiXnFqCgVe4zXkXaBs6iM9GQa+cXl267z6WjSYJ5C+GJXDwsnAgnDop9XoUxmyjiHeN0nULY20Uh6HNcdNkyAUte/YMxTZkltxtU7GpnkzWjssGX6e0DIRXNKaCdtBhENgIDoFrkGWHUsKW7DRPyJAuXfxhXlEx4Sm9536Q1naPyWSlLPOJWacf5i1aOXGDsYj7iB6BwvL3Ftde3pd/rXphuMOkvjLAXIw6mUPTZh7tsw0MdVNJEBLfouQ+H4NfJFcTEsEPbl4vUTXDqXtr/I5mP6MjLaFTqMRdYYbUai1ae7fpWs/IgRMAR+ls8qD62KOvkA9lntpCAJNlTKAJ/6sGOapZyRUQgFBbmXMF+t07unJZ8e6oZG1ALtDJaB8Jxy3/k2Q4VpKQaZKNkz25uXF2chEovrK9aoItbZpQh525k5xeXKctnTM4LLSoD7ORN3Vhds8NdSC/Wa1dQAURTJu1zerYdKsy9dOiuO5tktnSX6Tn4LgPiY47Qcab8Riu89+9vFgqXKhapsPufHiOgdHUIzdNPDfocXLGSB1t3akZfRsFlJV8NA7I/SSd6Q6DeS3cQWXwxl1pO9WBYZZuJdDT4O266MRy/Lsqa1Sf5dk06ZKPp4kcfnVa1NZTrsftdaGih5IdqQnNn+W3A5OZMc0Dw4ZbwZeB5uyG0H8mgDR2wAtU7pPFGBjhT9S4IoCbBa1JfgtO8ZpgpX4CkK1jtmZsYwtFKg+9UpL0XWV1AhPlb55AAKRWzM1QiknDwXHKWarF2JZI/sgvYjjN82Qeq1eChShRsbS7ypcJ4YmAFmvIlM6f4ZL+k3QOWXxXXVlfMwTSn4UXzqDHuuTErMxoA9aUo8ejGFuTwUCIDUVl/jrlb7tWkbDEf6YOvshn18PT+fQq7ycTzleYpJpHgCMqsq3cB9JfR55z83MSM9bC5K9TFLbS/gECLWi7yjZpQAzrIuVbd7GWG+0hQaRCPzTEMmdvWDjNfHtvwjb5aQALLF0fDOB21kRDMPpQtDdYPv02s9S+5dhZ+EXkyxUE7oBOCwQV0+O+f0IJWps33q9q6cNIjGE/3rP4hOjfe4IBrPrlDNRjqtkH09X0sgHWktLUh7AY3+ndzqCEvyjCFtWxp1ed3brikV2jeD5TWaYT6IBZdhCTGSCgq0W7Pkoc2sJvEPKOZguOJRZQODf+wHJQXuMwndVwRTRQ8TselLZ1sykSG9DfBsHjnH0hBid+crSO7Cluqww13bhB6g52lF+BuenqSbu1c0zZUsc7lyqnVSlA/IhX3zVIgjxf2ZHLJPwKsyYPDapchBnYQNB6pxzGdYN8FB0puzweh0HWf/yqpI1MrpSlSXiJC5EXZpg+OTPf1bpu6SZFTgrnjfOm4Af7BNSiIiVsEtVkPLTgTM9Gx/FyM0+PAoVjWVCO0
matrix:
  fast_finish: true

install:
- ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
- ps: $fileContent += $env:priv_key.Replace(' ', "`n")
- ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
- ps: Set-Content $env:userprofile\.ssh\id_rsa $fileContent
- git submodule update --init --recursive

# skip unsupported combinations
init:
- set cmake_arch=
- if "%arch%"=="Win64" (set cmake_arch= Win64)
- if "%arch%"=="Win32" (set cmake_arch=)
- echo %cmake_arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%cmake_arch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
build:
  project: c:\projects\cmake-init\build\tycho_ipl.sln
  verbosity: minimal
  parallel: true
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - src/
    - driver/
    - 3rdparty/
